### ISSUE TITLE
Review of Spring-API application

### ISSUE THREAD

**Issue by mandyWW** [shaniefrater/module-1#2]
Excellent work Shanie, you have managed to create a Spring Boot application with endpoints to CRUD a resource and also understand how to encrypt data and how to hash a password.

Comments:
Expand your Spring Boot application to include:

- returning correct HTTP status codes (rather than 200 as a default)
- integrate with a database (I will show you all how to do this next week)

Also, please exclude /target directory from being added to git by adding this to your .gitignore file.

**Comment by shaniefrater** [comment]
Thank you! Still needing to integrate with Database but we're looking to cover this week. All changes requested have been made! :)
